
# to activate overlay, write to this FIFO pipe
fifo_pipe_path: "/tmp/shortcut-overlay-pipe"


# list of paths containing keyboard shortcuts (.md and/or .yaml files)
shortcut_data_directories:
  - "/home/rossr/Documents/notes_mounted/Staying_Organized/Keyboard_Shortcuts"


daemon:
  # fallback to this app id when no windows are open. This is useful for displaying system-wide shortcuts.
  fallback_app_id: "cosmic_desktop"


ui:
  css_scale: 1.5
  screenshot_scale: 1.0

# Output paths
output:
  output_dir: "./output"
  gallery_path: "./output/gallery.html"
  scraper_shot_config_path: "./output/shots.yaml"


# Asset Pointers
assets:
  js_path: "./vendor_assets/shortcut-plugin/src/ui/view.js"
  css_path: "./vendor_assets/shortcut-plugin/src/ui/view.css"